name: giffy_dialog
description: A Flutter package for a quick, handy and beautiful giffy dialog.
version: 1.8.0
homepage: https://github.com/xsahil03x/giffy_dialog

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  google_fonts: ^2.1.0
  path_provider: ^2.0.2
  flare_flutter: ^3.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  image_test_utils: ^1.0.0

flutter: